### ISSUE TITLE
Could WebAssembly.Function instead be defined in terms of the Typed Object API?

### ISSUE THREAD

**Issue by lukewagner** [WebAssembly/js-types#1]
My assumption with the [wasm GC proposal](https://github.com/WebAssembly/gc/blob/master/proposals/gc/Overview.md) is that wasm GC objects will be reflected in JS as [Typed Objects](https://github.com/tschneidereit/typed-objects-explainer) which we'd co-standardize with TC39.

That implies that, for each wasm type that can be used as a field of a wasm GC object, we'd need a corresponding "thing" in Typed Objects.  This includes [typed function references](https://github.com/WebAssembly/reference-types/blob/master/proposals/reference-types/Overview.md#typed-function-references).  When you think of what a typed function reference would look like in JS, it's basically an exported wasm function: a rigid signature and, if you attempted to construct one from an arbitrary JS function, that JS function would get wrapped in the way that wasm wraps imported JS functions.

**Comment by rossberg** [comment]
Isn't that orthogonal? Function exports exist already, independent of reference types or Typed Objects. WebAssembly.Function would just make their handling symmetric to the other export types, i.e., tables, memories, and globals.

Reference values are not the same as export values. There can be references to Wasm functions, and they would be reflected directly as the underlying Wasm function objects. But that is only because the JS side does not make a distinction between a function and a reference to a function.

Conversely, consider an analogous addition of, say, references to tables, which we might want in the future to support first-class tables. Such references would likewise be directly reflected as WebAssembly.Table objects in JS. It seems like you're implying that at that point the Typed Objects API would need to know about Wasm's Table class, or even adopt it?

**Comment by lukewagner** [comment]
> It seems like you're implying that at that point the Typed Objects API would need to know about Wasm's Table class, or even adopt it?

No, the reference type there would, properly, be a "reference to a webassembly table".  The question I had was if there was (eventually) a JS-wide notion of "typed function" (as in signature+untyped-JS-callee, defined by the Typed Object API), couldn't we just reuse that.

Symmetry with the other wasm export kinds is a good argument, though.  Also, maybe one day we want to do something special for webassembly functions that doesn't apply to other purely JS typed function.

If a "typed function" concept was defined as part of typed objects, I suppose `WebAssembly.Function` could just be redefined to be a refinement of it.

**Comment by chicoxyzzy** [comment]
> Also, maybe one day we want to do something special for webassembly functions that doesn't apply to other purely JS typed function.

There is already https://github.com/WebAssembly/multi-value which could be non-applicable to JS if I understand this proposal correctly.
